### ISSUE TITLE
Sending JSON RPC: `system_health` causes panic in `runtime-parachain_testnet`

### ISSUE THREAD

**Issue by villenaj** [smol-dot/smoldot#1765] opened 2024-04-16 08:43 UTC
I tried filtering this `system_health` JSON RPC on message connection and the node run but also stops at 
```
Worker error:
Worker terminated due to reaching memory limit: JS heap out of memory
Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
    at [kOnExit] (node:internal/worker:313:26)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
```

And when I don't filter the `system_health` JSON RPC, it run with just a minute and panics at 
```
Smoldot has panicked while executing task `runtime-parachain_testnet`. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at /.../.../smoldot/light-base/src/runtime_service.rs:1866:35:
called `Option::unwrap()` on a `None` value
```

```
Worker error:

Error
    at panic (file:///.../.../smoldot/wasm-node/javascript/dist/mjs/internals/local-instance.js:57:23)
    at rust_begin_unwind (wasm://wasm/0d5f6186:wasm-function[3391]:0x29b748)
    at _ZN4core9panicking9panic_fmt17h87755523850ece9eE (wasm://wasm/0d5f6186:wasm-function[8265]:0x52a950)
    at _ZN4core9panicking5panic17hf4ba1575e20e9f91E (wasm://wasm/0d5f6186:wasm-function[8270]:0x52af14)
    at _ZN13smoldot_light15runtime_service14run_background28_$u7b$$u7b$closure$u7d$$u7d$17h573cc08294b7c32eE (wasm://wasm/0d5f6186:wasm-function[990]:0x94b10)
    at _ZN182_$LT$$LT$smoldot_light_wasm..platform..PlatformRef$u20$as$u20$smoldot_light..platform..PlatformRef$GT$..spawn_task..FutureAdapter$LT$F$GT$$u20$as$u20$core..future..future..Future$GT$4poll17hd571696facc5706fE (wasm://wasm/0d5f6186:wasm-function[1255]:0xeabaf)
    at _ZN10async_task3raw28RawTask$LT$F$C$T$C$S$C$M$GT$3run17h9bb8de159894a44cE.llvm.2845945349022015119 (wasm://wasm/0d5f6186:wasm-function[809]:0x6b3a8)
    at advance_execution (wasm://wasm/0d5f6186:wasm-function[3465]:0x2a55c4)
    at Module.<anonymous> (file:///.../.../smoldot/wasm-node/javascript/dist/mjs/internals/local-instance.js:313:40)
    at Generator.next (<anonymous>)
^Cfile:///.../.../smoldot/wasm-node/javascript/dist/mjs/internals/client.js:82
                    error: new CrashError(event.message),
                           ^

CrashError: panicked at /.../.../smoldot/light-base/src/runtime_service.rs:1866:35:
called `Option::unwrap()` on a `None` value
    at Object.eventCallback (file:///.../.../smoldot/wasm-node/javascript/dist/mjs/internals/client.js:82:28)
    at portToServer.onmessage (file:///.../.../smoldot/wasm-node/javascript/dist/mjs/internals/remote-instance.js:144:20)
    at MessagePort.eventHandler (node:internal/event_target:1106:12)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
```

**Comment by tomaka** [comment] 2024-04-16 08:54
In the situation where you do send `system_health`, could you provide me with the `debug`-level logs?

If you're using smoldot directly, this is done by passing `maxLogLevel: 4` to the `start()` function.
If not using smoldot directly, it depends on which wrapper you're using.

**Comment by tomaka** [comment] 2024-04-29 07:55
The `system_health`-related error is a duplicate of #1712

**Comment by tomaka** [comment] 2024-05-29 08:51
Closing as OP is non-responsive, and the other issue is fixed.

**Closed by tomaka** 2024-05-29 08:51 UTC
