### ISSUE TITLE
TrieVersion 1 supported?

### ISSUE THREAD

**Issue by ermalkaleci** [smol-dot/smoldot#221] opened 2023-02-23 11:16 UTC
Is trie version 1 fully supported? Using [chopsticks](https://github.com/AcalaNetwork/chopsticks) with Westend I am getting `Error while executing Wasm VM: Host function not implemented: ext_storage_root_version_2` and ProofBuilder seems like its producing invalid proof nodes

**Comment by tomaka** [comment] 2023-02-23 11:54
This is a duplicate of #78, but let's keep this issue as its title is better.

The answer is no, it's not fully supported.

`ext_storage_root_version_2` itself is very easy to implement, however the rest of codebase isn't ready. The two main areas that remain to do are:

- The code that calculates the trie root hash isn't fully aware of trie version 1 yet. The code that calculates a trie node value/hash is already aware of version 1, so it's mostly about making the calculation cache also cache the version of each node.
- The database doesn't store the version of each storage item.

**Comment by ermalkaleci** [comment] 2023-02-24 21:13
I got ProofBuilder working by providing all required validation data. Not sure if it's related to V1 but at least I got it working :)

**Closed** 2023-02-27 09:38 UTC
