### ISSUE TITLE
`state_getKeysPaged` times out (with small pages)

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#692] opened 2023-06-07 19:14 UTC
In some instances the `state_getKeysPaged` RPC call times out, even when requesting very small items.

For instance, when trying to retrieve the keys of the storage entry `Staking.Nominators`, the following request:

```js
{
  id: 'thisOneFails',
  jsonrpc: '2.0',
  method: 'state_getKeysPaged',
  params: [
    '0x5f3e4907f716ac89b6347d15ececedca9c6a637f62ae2af1c7e31eed7e96be04',
    2,
    '0x5f3e4907f716ac89b6347d15ececedca9c6a637f62ae2af1c7e31eed7e96be04'
  ]
}
```

always fails.

However, the equivalent request for the `Staking.Validators` entry:

```js
 {
  id: 'thisOneWorks',
  jsonrpc: '2.0',
  method: 'state_getKeysPaged',
  params: [
    '0x5f3e4907f716ac89b6347d15ececedca88dcde934c658227ee1dfafcd6e16903',
    2,
    '0x5f3e4907f716ac89b6347d15ececedca88dcde934c658227ee1dfafcd6e16903'
  ]
}
```

works perfectly fine.

## [Here you can find a demonstration of this issue](https://stackblitz.com/edit/node-1xkbb6?file=index.js)

**Comment by tomaka** [comment] 2023-06-07 20:18
What do you mean by "timed out"? Is it a timeout enforced by PolkadotJS?

This RPC call is implemented by downloading every single key of the prefix then keeping only the appropriate count and the ones that follow the start key.
There's no way for a light client to implement this RPC call in an optimal way, which is why there's no equivalent in the new JSON-RPC API.
I can however try to optimize it a bit through guesswork.

**Comment by josepot** [comment] 2023-06-07 20:22
> What do you mean by "timed out"? Is it a timeout enforced by PolkadotJS?

Nope. I'm not using PolkadotJS, please [have a look at the demo that I've provided](https://stackblitz.com/edit/node-1xkbb6?file=index.js).

The response that I get from smoldot for the request that I've provided is:

```json
{
  "jsonrpc":"2.0",
  "id":"thisOneFails",
  "error":{"code":-32000,"message":"Storage query errors:\n- Timeout\n- Timeout"}
}
```

> I can however try to optimize it a bit through guesswork/heuristics.

That would be amazing! Because having the ability of accessing the Staking.Nominators entries is quite critical for many different dApss :pray:

Thanks @tomaka !

**Comment by tomaka** [comment] 2023-06-09 07:56
The time out is probably caused by the fact that the response is too large. This would be solved by finishing the transition to `state_version=1`, but also by splitting big requests into smaller ones.

**Comment by josepot** [comment] 2023-06-09 13:32
> This would be solved by finishing the transition to `state_version=1`

Sorry, but I'm not following, could you please elaborate on this? :pray: 

>  but also by splitting big requests into smaller ones

:thinking: how could I possibly do that? The example of the demo is only requesting for 2 keys?

**Comment by tomaka** [comment] 2023-06-09 13:53
These are just notes for myself, not addresses to you.

**Comment by josepot** [comment] 2023-09-07 11:57
FWIW querying the values of this exact same storage key with the new JSON-RPC API seems to work perfectly fine.

**Comment by josepot** [comment] 2023-09-29 21:46
> FWIW querying the values of this exact same storage key with the new JSON-RPC API seems to work perfectly fine.

I take this back... 😞 I mistakenly tried it against the `Staking.Validators` key while I thought that I was trying it against `Staking.Nominators`. I'm very sorry about that!

Trying a `descendantValues` storage query with the new JSON-RPC API with the `Staking.Nominators` key (`0x5f3e4907f716ac89b6347d15ececedca9c6a637f62ae2af1c7e31eed7e96be04`) results in the emission of the `operationInaccessible` event.

I get that fixing this could be pretty challenging, and I don’t want to be that person, but this issue is kinda holding up a demo I’m working on. If it's a big pain to sort out, I can shift the demo around a bit.

Any chance you could let me know if this is fixable, and what the timeline might look like?

Thanks a ton! 🙏

**Comment by tomaka** [comment] 2023-10-11 16:59
As mentioned in #1209, this issue is presumed fixed in v2.0.4 (https://github.com/smol-dot/smoldot/pull/1213).
I'm leaving this issue open so that you can confirm whether this is the case. If it is still not working, I'd need logs to debug.

**Comment by josepot** [comment] 2023-10-12 08:41
> As mentioned in #1209, this issue is presumed fixed in v2.0.4 (#1213). I'm leaving this issue open so that you can confirm whether this is the case. If it is still not working, I'd need logs to debug.

Unfortunately v2.0.4 does not only not fix this issue, but it also breaks some storage requests that were previously working. Basically, what I'm experimenting is: I receive an `operationStorageDone` event before I have received any storage items. I will setup a stackblitz POC to demo the issue. Do you prefer me to do that in a new issue or should I reuse this one?

**Comment by tomaka** [comment] 2023-10-12 08:51
Found the problem, and it was already there before #1209, just #1209 revealed it :grimacing:

**Comment by josepot** [comment] 2023-10-12 11:14
> ```js
> 0x5f3e4907f716ac89b6347d15ececedca9c6a637f62ae2af1c7e31eed7e96be04
> ```

2.0.5 fixed the issue introduced by 2.0.4. Unfortunately, though, with 2.0.5 I still get the `operationInaccessible` event when I try to query the `descendantValues` of `Staking.Nominators` 😞.

**Comment by tomaka** [comment] 2023-10-12 11:29
Please provide some `debug` (log level 4) logs.

**Comment by josepot** [comment] 2023-10-12 12:25
> Please provide some `debug` (log level 4) logs.

here you go:
[logs.txt](https://github.com/smol-dot/smoldot/files/12882274/logs.txt)

**Comment by tomaka** [comment] 2023-10-12 12:42
> > Please provide some `debug` (log level 4) logs.
> 
> here you go: [logs.txt](https://github.com/smol-dot/smoldot/files/12882274/logs.txt)

Is this all? I don't see any event being sent back regarding the `chainHead_storage` after the `started` event.
It seems that the logs end when the request was still ongoing.

**Comment by josepot** [comment] 2023-10-12 12:52
> > > Please provide some `debug` (log level 4) logs.
> > 
> > 
> > here you go: [logs.txt](https://github.com/smol-dot/smoldot/files/12882274/logs.txt)
> 
> Is this all? I don't see any event being sent back regarding the `chainHead_storage` after the `started` event. It seems that the logs end when the request was still ongoing.

The last log:

> [json-rpc-polkadot] JSON-RPC <= {"jsonrpc":"2.0","method":"chainHead_unstable_followEvent","params":{"subscription":"1","result":{"e…

is the `operationInaccessible` event.

**Comment by tomaka** [comment] 2023-10-12 13:05
Ah right I forgot that the storage events were now reported as `chainHead_follow`

**Comment by tomaka** [comment] 2023-10-13 11:55
Note for self: here's the small demo tweak I use to test this:

```rust
defaultChain.then(async (chain) => {
    chain.sendJsonRpc('{"jsonrpc":"2.0","id":1,"method":"chainHead_unstable_follow","params":[true]}');
    const subId = JSON.parse(await chain.nextJsonRpcResponse()).result;
    const finHash = JSON.parse(await chain.nextJsonRpcResponse()).params.result.finalizedBlockHash;
    chain.sendJsonRpc('{"jsonrpc":"2.0","id":2,"method":"chainHead_unstable_storage","params":["1","' + finHash + '",[{"key":"0x5f3e4907f716ac89b6347d15ececedca9c6a637f62ae2af1c7e31eed7e96be04","type":"descendantsValues"}],null]}');
    while (true) {
        const resp = JSON.parse(await chain.nextJsonRpcResponse());
        if (resp.params && resp.params.result.event.startsWith('operation'))
            console.log(resp);
    }
});
```

It might become useful later.

**Comment by josepot** [comment] 2023-10-16 09:32
It seems that 2.0.6 fixes this issue 🎉  Should I close this @tomaka ?

**Closed** 2023-10-16 09:40 UTC
