### ISSUE TITLE
panicked at 'called `Result::unwrap()` on an `Err` value: UnknownAddress', /__w/smoldot/smoldot/light-base/src/network_service.rs:1556:22

### ISSUE THREAD

**Issue by kratico** [smol-dot/smoldot#1405] opened 2023-11-24 13:44 UTC
panicked at 'called `Result::unwrap()` on an `Err` value: UnknownAddress', /__w/smoldot/smoldot/light-base/src/network_service.rs:1556:22

Attaching logs [smoldot-v2.0.10.log](https://github.com/smol-dot/smoldot/files/13459683/smoldot-v2.0.10.log)

This seems to be similar to https://github.com/smol-dot/smoldot/issues/1330 but with `smoldot@2.0.10`

**Comment by tomaka** [comment] 2023-11-24 13:57
I don't know if this is the cause, but I've recently found one possible cause and added it as a TODO: https://github.com/smol-dot/smoldot/blob/dba82431f8d8577990ce859bb6420e420230dc68/light-base/src/network_service.rs#L1602

**Comment by tomaka** [comment] 2023-11-24 14:12
It's unfortunately very hard to figure out the possible problem, as I've done tons of changes to the networking service recently. For this reason, I want to go bug-hunting a bit before releasing a new version.

The logs aren't very useful (they don't indicate which peer causes the panic). Most likely I'll never find the problem here, and instead hope that a new version fixes it.

**Comment by kratico** [comment] 2023-11-24 15:08
Thx @tomaka 

Is the `maxLogLevel: 4` good enough?

Or, Would it help if I increase the log level to `5`?

**Comment by tomaka** [comment] 2023-11-24 15:13
No, the log line would be printed after the panic and so is never reached.

**Comment by tomaka** [comment] 2023-11-28 13:58
Closing in favor of #1429

**Closed by tomaka** 2023-11-28 13:58 UTC
