### ISSUE TITLE
Panic error `assertion failed: self.input_best_block_index.map_or`

### ISSUE THREAD

**Issue by tien** [smol-dot/smoldot#1934] opened 2024-08-08 23:02 UTC
I've received the following issues somewhat often with smoldot

```console
Smoldot has panicked while executing task `sync-service-asset-hub-polkadot`. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at /__w/smoldot/smoldot/lib/src/chain/async_tree.rs:866:9:
assertion failed: self.input_best_block_index.map_or(false,
    |current_input_best|
        self.non_finalized_blocks.is_ancestor(node_to_finalize,
            current_input_best)) client.js:75:24
```

The issue appear to happen if you lazily add parachains (Hard to tell because I can't consistently reproduce this error).

This seems to work fine (so far):

```ts
const relayChain = smoldot.addChain({ chainSpec: relayChainSpec });
const parachain = smoldot.addChain({ chainSpec: parachainSpec, potentialRelayChains: [relayChain] });
```

But this will occasionally raise the panic error:

```ts
const relayChain = smoldot.addChain({ chainSpec: relayChainSpec });

// Will only be called if parachain interaction is needed
const getParachain = () => smoldot.addChain({ chainSpec: parachainSpec, potentialRelayChains: [relayChain] });
```

**Comment by tomaka** [comment] 2024-08-12 14:14
This is most likely a duplicate of https://github.com/smol-dot/smoldot/issues/1901, which *might* be fixed but the fix unreleased. If you have a way to generate logs when the problem happens, it would be very helpful.

**Closed by tomaka** 2024-08-12 14:14 UTC
