### ISSUE TITLE
Smoldot has panicked while executing task `network-service`.

### ISSUE THREAD

**Issue by Douglasacost** [smol-dot/smoldot#1090] opened 2023-08-30 14:35 UTC
Hello guys, recently I'm having some errors some seconds after a connection

As the error shows is panicked and should be reported, here the data

This is happening while getting connected to a parachain

<img width="883" alt="Screenshot 2023-08-30 at 8 14 27 AM" src="https://github.com/smol-dot/smoldot/assets/10488928/f7709fb1-a0bc-47bb-84c0-000820d318a1">

Node version: v18.17.0
Smoldot version: 1.0.17

**Comment by tomaka** [comment] 2023-09-04 06:52
Duplicate of https://github.com/smol-dot/smoldot/issues/381

(I've never taken the time to fix https://github.com/smol-dot/smoldot/issues/381 as it's not supposed to ever happen on a real chain)

**Comment by tomaka** [comment] 2023-09-11 09:17
I can't manage to reproduce. Do you have a reliable way of making it happen, by any chance?

**Comment by tomaka** [comment] 2023-09-11 09:18
As a side-note, this code is over-complicated, making it hard to figure out the problem. The plan is for #478 to simplify it.

**Comment by skunert** [comment] 2023-09-15 13:05
I also ran into this bug today on a zombienet test in CI. I think I have seen the error before but it seems to happen rarely.
Logs attached, but not very insightful sadly (Exported from loki, so starts from bottom).
[Explore-logs-2023-09-15 13_46_37.txt](https://github.com/smol-dot/smoldot/files/12619588/Explore-logs-2023-09-15.13_46_37.txt)

**Closed** 2023-10-27 13:08 UTC
