### ISSUE TITLE
GrandPa warp sync times out on github CI

### ISSUE THREAD

**Issue by lexnv** [smol-dot/smoldot#1562] opened 2024-01-08 14:25 UTC
We have recently encountered a few subxt github CI timeouts with the light client.
GrandPa warp sync seems to be idle at the same block until the CI times out our testing.
This is happening in a flaky manner and could be reproduced by https://github.com/paritytech/subxt/pull/1346. 

Smoldot version is 0.15 and smoldot-light is 0.13 (from [Cargo.toml](https://github.com/paritytech/subxt/blob/c5948dc967e0e56a403de807bc104f0129c2ff2e/Cargo.toml#L104C1-L105C65)).
The test connects the smoldot client to the polkadot network from a freshly downloaded chainSpec; then performs a few subscriptions and method requests. 

Logs reported by the [subxt](https://github.com/paritytech/subxt/blob/745403ca29b0b4a1aac0360ad69d9b21962f7b08/testing/integration-tests/src/light_client/mod.rs#L147) test:

```bash
2024-01-08T13:22:48.947771Z  WARN json-rpc-polkadot: The JSON-RPC client has just called a JSON-RPC function from the legacy JSON-RPC API (chain_getFinalizedHead). Legacy JSON-RPC functions have loose semantics and cannot be properly implemented on a light client. You are encouraged to use the new JSON-RPC API <https://github.com/paritytech/json-rpc-interface-spec/> instead. The legacy JSON-RPC API functions will be deprecated and removed in the distant future.    
...

2024-01-08T13:22:58.947182Z  WARN sync-service-polkadot: GrandPa warp sync idle at block #18952945 (0x0xfde5…4433)    
...

2024-01-08T13:25:38.948843Z  WARN sync-service-polkadot: GrandPa warp sync idle at block #18952945 (0x0xfde5…4433)    
...

2024-01-08T13:37:58.956476Z  WARN sync-service-polkadot: GrandPa warp sync idle at block #18952945 (0x0xfde5…4433)    
 Error: The operation was canceled.
```

Logs extracted from: https://github.com/paritytech/subxt/actions/runs/7447975422/job/20261334692?pr=1346

Let me know if I could provide more details here, thanks! 🙏

**Comment by tomaka** [comment] 2024-01-08 14:41
You've set `sync-service-polkadot=info` in the logging settings for some reason. This unfortunately hides the log entries that would be useful for debugging this.

**Comment by lexnv** [comment] 2024-01-08 16:24
I was able to reproduce it with `syn-service-polkadot=trace` with two entries 🙏 
- https://github.com/paritytech/subxt/actions/runs/7449024220/job/20267615569?pr=1346 (Test 1 and Test 3)

**Comment by tomaka** [comment] 2024-01-08 17:07
Thanks!

What happens is that when we connect to peers, their finalized block is equal to the block of the checkpoint in the chain spec.
For this reason, smoldot doesn't start any warp sync request, as it's already at the head of the chain.
In principle it still needs to perform the rest of the warp sync process, as otherwise it can't sync further block, but it just doesn't.

In principle, the nodes we're connected to should at some point finalize another block and send a commit message to smoldot, which would make smoldot start the warp syncing, but for some reason they don't and I'm not sure why.

**Comment by tomaka** [comment] 2024-01-08 17:10
I vaguely remember fixing a `>` that should be a `>=` in the warp syncing code in a recent PR, but I can't find it.
It's possible that this issue is already fixed in the more recent version of smoldot.

**Comment by lexnv** [comment] 2024-01-11 12:46
Hey, thanks for looking into this! 

I managed to reproduce this in a new [PR](https://github.com/paritytech/subxt/pull/1355) which uses the git-dependency smoldot from the latest branch with this [commit](https://github.com/smol-dot/smoldot/commit/e02844c32cfa673b0fb4130a4af50152645eeafe). Logs are available at: https://github.com/paritytech/subxt/actions/runs/7488555076/job/20383286368?pr=1355

```
2024-01-11T12:16:58.851770Z  WARN sync-service-polkadot: GrandPa warp sync idle at block #18995151 (0x0x000f…8d36) 
 ...
2024-01-11T12:29:38.861440Z  WARN sync-service-polkadot: GrandPa warp sync idle at block #18995151 (0x0x000f…8d36) 
...
2024-01-11T12:31:48.863079Z  WARN sync-service-polkadot: GrandPa warp sync idle at block #18995151 (0x0x000f…8d36) 
```

Let me know if I could provide more details, thanks 🙏

**Comment by tomaka** [comment] 2024-01-11 21:05
> In principle it still needs to perform the rest of the warp sync process, as otherwise it can't sync further block, but it just doesn't.

This was actually not true.

The checkpoint contains everything needed to start syncing properly, so there's no need to do any warp sync at all.

The issue is actually that the warp sync code is basically in the middle of a refactoring.
The warp sync code is now designed to pause itself when there's nothing to warp sync to (like in this case), however the code on top of it still waits for the initial warp sync to succeed before it starts syncing blocks on top.

This issue would be fixed by https://github.com/smol-dot/smoldot/issues/1109, as it basically consists in finishing that refactoring, but that issue is non-trivial. It's not clear to me from the top of my head whether a temporary intermediary fix is easy or not.

**Closed** 2024-01-20 10:05 UTC
